"""The big test set for the Jev duplicate check (written 1 Oct 2026, before any tuning on it).

Each case: (suggestion, expected, accepted ids, style)
  expected: "duplicate" | "new" | "?" (borderline: reported, never scored)
  accepted ids: for duplicates, every bank idea a fair reviewer would accept, "i015|i081";
                for borderline cases, the closest idea (for information only)
  style: plain | informal | short | lang (not English) | near (a new idea that looks like a bank idea)

It's split in two by a fixed rule (see split()): TUNE for improving the algorithm, TEST for scoring it
once at the end. Never tune on TEST."""
import hashlib

CASES = [
    # ------------------------------------------------------------------ duplicates, one or two per bank idea
    ("tap the tag by my kitchen speaker and the podcast I'm listening to on my phone continues there", "duplicate", "i001", "plain"),
    ("move whatever's playing from my phone to the living room sonos with one tap", "duplicate", "i001", "informal"),
    ("my garage motion sensor turns the lights off while I'm working at the bench, a tap should keep them on", "duplicate", "i002", "plain"),
    ("labels for my storage bins: tapping one shows a photo of what's in that bin", "duplicate", "i003", "plain"),
    ("sticker on the water filter jug, tap when I change the filter and get reminded in 2 months", "duplicate", "i004", "plain"),
    ("tap when i replace my toothbrush head so phone tells me when its time again", "duplicate", "i004", "informal"),
    ("when friends come over one tap turns off the motion sensor lights and the doorbell notifications", "duplicate", "i005", "plain"),
    ("tag on the kettle that starts a 4 minute tea timer", "duplicate", "i006", "plain"),
    ("tap on the washing machine = 90 min timer so I remember the laundry", "duplicate", "i006", "informal"),
    ("sticker on the bathroom mirror that starts a 2-minute toothbrushing timer for the kids", "duplicate", "i006", "plain"),
    ("unlock my nuki smart lock by tapping a sticker next to the door", "duplicate", "i007", "plain"),
    ("tag on the garden shed's smart padlock so I can open it with my phone", "duplicate", "i007", "plain"),
    ("one tap at the front door when I go out: all lights off, thermostat down, vacuum starts", "duplicate", "i008", "plain"),
    ("coming home I tap a tag in the hallway: lights on, wifi on, phone silent, heating back up", "duplicate", "i009", "plain"),
    ("goodnight tag on the bedside table: every lamp off and phone to sleep mode", "duplicate", "i010", "plain"),
    ("same tag does different things: at night it turns on a dim hallway light, in the morning it starts my morning routine", "duplicate", "i011", "plain"),
    ("tag next to my daughter's light switch, dims the lights and plays lullabies at bedtime", "duplicate", "i012", "plain"),
    ("nfc sticker as a fake light switch for a lamp I can't reach", "duplicate", "i013", "informal"),
    ("movie night tag under the coffee table: dims the lights and puts on chill music", "duplicate", "i014", "plain"),
    ("CD cases with tags so my kid taps one and that album plays on the speaker", "duplicate", "i015|i081", "plain"),
    ("tap the sticker on the shelf and my morning playlist starts on the speaker", "duplicate", "i016", "plain"),
    ("tag in each plant pot that shows how often to water it and how much sun it needs", "duplicate", "i017", "plain"),
    ("tap the watering can after watering so it gets logged", "duplicate", "i017", "short"),
    ("bin day reminder keeps nagging until I tap the sticker on the wheelie bin", "duplicate", "i018", "plain"),
    ("if I'm stuck in the bathroom without toilet paper, tap a tag and alexa announces it to the whole house", "duplicate", "i019", "informal"),
    ("tag on the fuse box that opens a video showing which fuse is which and how to reset one", "duplicate", "i020", "plain"),
    ("sticker on the baby car seat that opens the installation manual", "duplicate", "i020", "plain"),
    ("tag on the tent bag that opens a video of how to pitch the tent", "duplicate", "i020", "plain"),
    ("by the patio door: tap to start the sprinklers for 30 minutes", "duplicate", "i021", "plain"),
    ("tag on the thermostat that puts the heating in away mode while we're on holiday", "duplicate", "i021|i008", "plain"),
    ("when the olive oil bottle is empty I tap it and it goes on my shopping list", "duplicate", "i022", "plain"),
    ("tag inside my gym bag opens a list: towel, shoes, lock, water bottle", "duplicate", "i023", "plain"),
    ("my alarm won't stop until i scan the tag in the kitchen, so I actually have to get up", "duplicate", "i024", "informal"),
    ("tap by the coffee machine and my phone reads my calendar for the day out loud", "duplicate", "i025", "plain"),
    ("track caffeine: tap the espresso machine and it logs a coffee in apple health", "duplicate", "i027", "informal"),
    ("tap the vitamin bottle after taking one so I don't take them twice", "duplicate", "i028", "plain"),
    ("sticker under my prescription bottle opens the pharmacy refill page", "duplicate", "i029", "plain"),
    ("tap my yoga mat: blinds close, lights dim, yoga video starts", "duplicate", "i030", "plain"),
    ("pomodoro tag on the desk, starts a 25 min focus timer and mutes notifications", "duplicate", "i031", "informal"),
    ("i block social media and the only way to unblock it is to scan a tag in another room", "duplicate", "i032", "informal"),
    ("keychain tag that starts dictation so I can quickly record ideas as a note", "duplicate", "i033", "plain"),
    ("tag in my bullet journal opens my digital planner and plays lo-fi music", "duplicate", "i034", "plain"),
    ("tag on the bathroom scale that opens my weight tracking app", "duplicate", "i035", "plain"),
    ("tag on my guitar case that opens the tuner app", "duplicate", "i035", "plain"),
    ("tap the desk to wake my gaming PC and turn on the LED strip", "duplicate", "i036", "plain"),
    ("sticker on my macbook so one tap shares my phone's internet with it", "duplicate", "i037", "plain"),
    ("tag that turns on the VPN and bluetooth at the same time", "duplicate", "i038", "plain"),
    ("tag by the front door that switches my ringer back to loud when I go out", "duplicate", "i038|i008", "plain"),
    ("a tag that sends the SMS to my bank asking for my balance", "duplicate", "i039", "plain"),
    ("phone holder in the car has a tag, waze and my podcast start when I put the phone in", "duplicate", "i040", "informal"),
    ("tap a tag when I get to the office and my mom gets an 'arrived safe' text", "duplicate", "i041", "plain"),
    ("tag on the dashboard that opens the driveway gate", "duplicate", "i042", "short"),
    ("coaster in my hair salon so clients join the wifi without asking for the password", "duplicate", "i043", "plain"),
    ("nfc business card that opens my linkedin", "duplicate", "i044", "short"),
    ("tag behind a small frame on my wall that opens a note with all my social media links", "duplicate", "i045", "plain"),
    ("tag on my dog's collar so anyone who finds him can see my phone number", "duplicate", "i046", "plain"),
    ("sticker on my suitcase with my contact info in case the airline loses it", "duplicate", "i046", "plain"),
    ("put a tag inside a necklace box, when she taps it my voice message plays", "duplicate", "i047", "plain"),
    ("tag on our takeaway bags that sends customers to our tripadvisor review page", "duplicate", "i049", "plain"),
    ("cafe tables with a tag that shows the menu", "duplicate", "i050", "short"),
    ("tag on my candle packaging so buyers can read the burn instructions and ingredients", "duplicate", "i051", "plain"),
    ("tags on supermarket shelf labels that show the allergens of each product", "duplicate", "i051", "plain"),
    ("a sign at my market stall: tap to follow my instagram", "duplicate", "i052", "plain"),
    ("concert poster with an nfc spot that opens the ticket page", "duplicate", "i053", "plain"),
    ("branded pens for our dental clinic that open the booking page when tapped", "duplicate", "i054", "plain"),
    ("hidden tags under the tables in our family restaurant that kids tap to play games while waiting", "duplicate", "i055", "plain"),
    ("tag on the 'for rent' sign outside the apartment that shows photos and the price", "duplicate", "i056", "plain"),
    ("security guards tap checkpoints during their night round and every tap is logged with the time", "duplicate", "i057", "plain"),
    ("cleaners tap the tag in each hotel room when it's done, and can flag low supplies", "duplicate", "i058", "plain"),
    ("truck drivers tap tags on tyres and lights during the pre-trip inspection", "duplicate", "i059", "plain"),
    ("patients wear wristbands with a chip, nurses tap them to see the patient's info", "duplicate", "i060", "plain"),
    ("scan the patient's wristband and then the medicine to check it's the right dose", "duplicate", "i061", "plain"),
    ("luxury handbag with a chip you tap to check it's not a fake", "duplicate", "i062", "plain"),
    ("vaccine shipments with a tag that records the temperature during transport", "duplicate", "i063", "plain"),
    ("pay for the metro by tapping my phone at the gate", "duplicate", "i064", "short"),
    ("university ID card on my phone to open doors and pay at the canteen", "duplicate", "i065", "plain"),
    ("hotel room key on my phone, I just tap the door", "duplicate", "i066", "short"),
    ("use my phone as the car key, tap the door handle to unlock", "duplicate", "i067", "plain"),
    ("passports have an NFC chip that the border control reads", "duplicate", "i068", "plain"),
    ("touch my phone to the headphones and they pair automatically", "duplicate", "i069|i088", "plain"),
    ("tap the TV remote with my phone to mirror my screen", "duplicate", "i070", "short"),
    ("tap the phone on the printer's nfc logo to print a photo", "duplicate", "i071", "plain"),
    ("for my blind mother: set the washing machine from an accessible app and tap to send the settings", "duplicate", "i072", "plain"),
    ("hold two phones back to back to share a contact", "duplicate", "i073", "short"),
    ("members of our climbing club tap their card at the entrance so we know who came", "duplicate", "i079", "plain"),
    ("kids top up credit on a card and pay at the school canteen by tapping", "duplicate", "i080", "plain"),
    ("my toddler taps a card with an animal picture and the story plays on the speaker, no screen", "duplicate", "i081", "plain"),
    ("evening check: tap a tag on each window and door so my phone confirms I checked them all", "duplicate", "i082", "plain"),
    ("tap at the door before leaving and the house tells me if any window is still open", "duplicate", "i084", "plain"),
    ("business idea: set up review cards for local shops and charge a monthly fee to keep their pages updated", "duplicate", "i085", "plain"),
    ("tag on my blood pressure monitor opens the log with today's date", "duplicate", "i087", "plain"),
    ("tag on my airpods case so my phone connects to them and starts my podcast", "duplicate", "i088|i069", "plain"),
    ("I tap my desk when I arrive and leave so my work hours are tracked", "duplicate", "i089", "plain"),
    ("chore tags around the house, the kids tap when a chore is done and earn points", "duplicate", "i090", "plain"),
    ("tag on my skincare shelf to mark my skincare routine as done in my habit tracker", "duplicate", "i091", "plain"),
    ("cat food tin has a sticker so we know if someone already fed the cat", "duplicate", "i092", "informal"),
    ("for my grandma: tap tags when she gets her meds and meals so all her caregivers see a log", "duplicate", "i093", "plain"),
    ("parking spot saver tag in my car", "duplicate", "i094", "short"),
    ("tag next to grandpa's bed that calls me with his location if he needs help", "duplicate", "i095", "plain"),
    ("scavenger hunt with nfc clues around the school for the kids", "duplicate", "i096", "informal"),
    ("world map on the wall with tags on the countries we visited, tap to see the photos", "duplicate", "i097", "plain"),
    ("tag in the hallway so the roborock cleans only the hallway", "duplicate", "i098", "plain"),
    ("tag on the fridge that opens our football team's match schedule", "duplicate", "i099", "plain"),
    ("tags on my 3D printer filament rolls show the material and how much is left", "duplicate", "i100", "plain"),
    ("magic the gathering cards in sleeves with tags that open the card rules", "duplicate", "i101", "plain"),
    ("tag on a board game box that opens a video explaining how to play", "duplicate", "i101|i020", "plain"),
    ("before zoom meetings I tap my desk: lights set, mic on, and an 'on air' light outside my door", "duplicate", "i103", "plain"),
    ("hidden tag at a party that plays a fart sound when tapped", "duplicate", "i104", "informal"),
    ("tag sewn into the scarf I knitted so people can see the pattern and the yarn", "duplicate", "i105", "plain"),
    ("tags in my clothes, tap when I wear something so I find out what I never wear", "duplicate", "i106", "plain"),
    ("home charging station only starts after tapping my tag so neighbours can't use my power", "duplicate", "i107", "plain"),
    ("tap the tag on my headboard so the espresso machine warms up before I get to the kitchen", "duplicate", "i108", "plain"),
    ("sticker on my handmade jewellery stand that opens my payment link", "duplicate", "i109", "plain"),
    ("when I leave, tap the tag by the door and the dog camera opens", "duplicate", "i110", "plain"),
    ("a payment ring so I can pay by tapping my finger at the card terminal", "duplicate", "i111", "plain"),
    # typos, run-on sentences, very short
    ("wifi for guests", "duplicate", "i043", "short"),
    ("pill tracker", "duplicate", "i028", "short"),
    ("tap to save where i parked", "duplicate", "i094", "short"),
    ("i put sticker on my keys and when i tap it i dont forget wallet phone and keys, it shows list", "duplicate", "i023", "informal"),
    ("so basically i have a tag on my nightstand and when i go to sleep i tap it and the lights go off and also my phone goes do not disturb, its really nice", "duplicate", "i010", "informal"),
    # other languages (Jev's docs say accuracy is lower outside English)
    ("pegatina en la mesita de noche: al tocarla se apagan todas las luces y el móvil pasa a modo no molestar", "duplicate", "i010", "lang"),
    ("una etiqueta en el posavasos para que los invitados se conecten al wifi sin escribir la contraseña", "duplicate", "i043", "lang"),
    ("tarra auton kojelautaan, joka tallentaa pysäköintipaikan kartalle", "duplicate", "i094", "lang"),
    ("NFC-Tag am Wasserkocher, der einen Timer für den Tee startet", "duplicate", "i006", "lang"),
    ("tarra roskikseen, joka hiljentää roskapäivän muistutuksen", "duplicate", "i018", "lang"),

    # ------------------------------------------------------------------ new ideas (not in the bank)
    ("tag on the front door of our Airbnb that opens the check-in guide, house rules and checkout time", "new", None, "plain"),
    ("tag on my running shoes: tap after each run to add the kilometres to that pair so I know when to replace them", "new", None, "near"),
    ("tag on the bird feeder: tap to log which birds I saw today", "new", None, "plain"),
    ("tag at the start of a hiking trail: hikers tap to see the trail map and today's conditions", "new", None, "plain"),
    ("tag on a park bench that plays a short story about the history of the place", "new", None, "plain"),
    ("tag on the shared flat fridge: tap to add what you bought to the flatmates' expense splitter", "new", None, "plain"),
    ("tags on the lunch menu board at work: tap your favourite to vote for Friday's lunch", "new", None, "plain"),
    ("tag on the pull-up bar: tap after each set to count my sets and reps", "new", None, "plain"),
    ("tap when I go to bed and when I wake up to log how many hours I slept", "new", None, "near"),
    ("tags on the wedding tables that open a page where guests upload their photos of the day", "new", None, "plain"),
    ("tag in the shared family car: tap at the start and end of a trip to log who drove and the mileage", "new", None, "near"),
    ("tag on the parking sign in town: tap to pay for parking in the city's app", "new", None, "plain"),
    ("tap the leftovers box to save when it was cooked and get a reminder before it goes bad", "new", None, "near"),
    ("tag on my synthesizer that loads my favourite sound preset", "new", None, "plain"),
    ("tag at the gym entrance to see how crowded the gym is right now", "new", None, "plain"),
    ("tags at the stops of a self-guided city walking tour, each one opens the story of that place", "new", None, "plain"),
    ("tag on my mailbox: tap to ask my neighbour to empty it while I'm on holiday", "new", None, "near"),
    ("tag on the car dashboard that starts recording dashcam video on my phone", "new", None, "plain"),
    ("tag on the shared washing machine in our building: tap to reserve the next free slot", "new", None, "plain"),
    ("tag on the stroller that shows the nearest baby changing room on the map", "new", None, "plain"),
    ("tag on the classroom door: students tap to answer the question of the day", "new", None, "plain"),
    ("tag on the solar panel inverter that shows how much power we made today", "new", None, "plain"),
    ("tag on the beehive that logs each inspection and honey harvest", "new", None, "plain"),
    ("tag under the restaurant table to split the bill between friends", "new", None, "plain"),
    ("tag on my front door so the delivery driver can leave a note that the parcel was delivered", "new", None, "plain"),
    ("tag on rental tools: the customer taps to start the rental timer and pays by the hour", "new", None, "plain"),
    ("tags on hotel minibar items so the guest is billed automatically when they take one", "new", None, "plain"),
    ("tag in the fitting room of a clothes shop so customers can ask for another size", "new", None, "plain"),
    ("tag in the elevator of our building to report to the caretaker that it's broken", "new", None, "plain"),
    ("tag on the bakery counter that shows which breads are still available today", "new", None, "plain"),
    ("tag on the car's fuel cap that logs litres and price to track fuel consumption", "new", None, "near"),
    ("tag on the dog's leash that starts tracking the walk route and time", "new", None, "near"),
    ("tag on the fridge that shows each family member's allergies for babysitters", "new", None, "plain"),
    ("tag on a hospital waiting room chair that shows your place in the queue", "new", None, "plain"),
    ("tag on my fishing rod that logs the water temperature and weather when I start fishing", "new", None, "plain"),

    # ------------------------------------------------------------------ borderline: a fair reviewer could go either way
    ("tag on the baby's changing table that logs each nappy change and feed for both parents", "?", "i093", "near"),
    ("tag on the aquarium to log water changes and feeding", "?", "i004", "near"),
    ("tag on each cinema seat to order snacks to your seat", "?", "i050", "near"),
    ("tags hidden in our escape room that unlock the next puzzle", "?", "i096", "near"),
    ("tag on the slow cooker that opens my favourite slow cooker recipe", "?", "i020", "near"),
    ("kids earn 30 minutes of tablet time by tapping the tag after finishing homework", "?", "i032", "near"),
    ("event staff tap attendees' wristbands to check them in at the door", "?", "i079", "near"),
    ("tag on the medicine cabinet that shows which medicines expire soon", "?", "i003", "near"),
    ("tag on my coffee bag that reorders the same beans from the roaster", "?", "i029", "near"),
    ("tags on the kitchen drawers for my blind dad, each one reads out what's inside", "?", "i003", "near"),
    ("tag on my motorbike helmet that connects the intercom and starts navigation", "?", "i040", "near"),
    ("tag on our boat that opens the safety checklist before leaving the harbour", "?", "i059", "near"),
    ("tag at the bus stop that shows when the next bus comes", "?", "i099", "near"),
    ("tag on my child's school bag that shows today's timetable", "?", "i099", "near"),
    ("tag on the fridge that shows this week's meal plan", "?", "i099", "near"),
    ("tag at our conference booth that adds visitors to our mailing list", "?", "i052", "near"),
    ("tags on the vegetable beds that show what's planted and when it was sown", "?", "i017", "near"),
    ("tag on a bottle of my homemade wine that shows the batch and bottling date", "?", "i105", "near"),
    ("tag on the sourdough starter jar to log when it was last fed", "?", "i092", "near"),
    ("tags on the houseplants I sell so customers can see the price and care tips", "?", "i051", "near"),
    ("tag on my desk plant that reminds me to water it every Monday", "?", "i017", "near"),
    ("tag on the fridge door: each of us taps to say 'I'm home' and the family chat sees who's in", "?", "i041", "near"),
]


# ------------------------------------------------------------------ NEAR: a third set, written after scoring TEST
# TEST showed the weak spot: look-alike new ideas. This set targets it, written before scoring any fix on it.
# Pre-registered decision: the version with fewer mistakes wins, a false duplicate counting double
# (it silently throws away someone's idea; a missed duplicate only adds a near-copy to the bank).
NEAR = [
    # look-alike new ideas: same object or mechanism as a bank idea, clearly different purpose
    ("tag on the kettle that tells my partner I'm making tea and asks if they want a cup", "new", None, "near"),
    ("tag on my nightstand that logs what time I went to bed, to track my sleep schedule", "new", None, "near"),
    ("sticker on the car dashboard that opens my insurance and roadside assistance numbers", "new", None, "near"),
    ("tag on the guest room door that shows guests where the towels are and the breakfast times", "new", None, "near"),
    ("tag on a library bookshelf that shows which books arrived this month", "new", None, "near"),
    ("tag on the pet carrier that opens my cat's vaccination record and pet passport", "new", None, "near"),
    ("tag on the office coffee machine that tells facilities it needs descaling", "new", None, "near"),
    ("tags on train seats so passengers can report a broken seat", "new", None, "near"),
    ("tag on my car key fob that opens the page to book the next car service", "new", None, "near"),
    ("tag on my e-reader case that starts reading the book out loud", "new", None, "near"),
    ("tag on my tennis bag that starts keeping score of my match", "new", None, "near"),
    ("tag on the window that starts a guided breathing exercise", "new", None, "near"),
    ("tag in my wallet that shows my blood donor card and donation history", "new", None, "near"),
    ("tag on the plant pot in my meditation corner that plays calming nature sounds", "new", None, "near"),
    ("tag on the stairs that counts how many times I climbed them today", "new", None, "near"),
    ("tag on a shared office desk: tap to book that desk for the day", "new", None, "near"),
    ("tag on the fridge that starts a video call with grandma", "new", None, "near"),
    ("tag on the car seat that reminds me there's a baby in the back when I leave the car", "new", None, "near"),
    ("tag on the bike rack at work that logs my cycling days for the company challenge", "new", None, "near"),
    ("tag on my laptop that locks the screen when I walk away", "new", None, "near"),
    ("tag on the wedding guest book that opens a page to record a video message for the couple", "new", None, "near"),
    ("tag on the wardrobe that suggests an outfit based on today's weather", "new", None, "near"),
    ("tag on a tree in the park that tells walkers what species it is", "new", None, "near"),
    ("tag on my keyboard that switches my computer between work and gaming profiles", "new", None, "near"),
    ("tag on the door of a public toilet to report that it needs cleaning", "new", None, "near"),
    ("tag on the kids' piggy bank that shows how much they've saved towards their goal", "new", None, "near"),
    # "one specific example" of a broader bank idea: these should stay duplicates
    ("tag on the shower wall that starts a 5-minute timer to save water", "duplicate", "i006", "plain"),
    ("tag on the speaker that plays a different radio station for each family member", "duplicate", "i016", "plain"),
    ("tag on my desk that turns on a 'do not disturb' light so the kids know I'm in a call", "duplicate", "i103|i031", "plain"),
    ("tag on the washing machine that shows the right program for each fabric", "duplicate", "i020", "plain"),
    ("tag on the medicine box that shows the leaflet in large print for my grandma", "duplicate", "i051|i020", "plain"),
    ("tag on my contact lens case to remember when I opened the new pair", "duplicate", "i004", "plain"),
    ("tag on the dog's water bowl so the family knows someone refilled it", "duplicate", "i092|i090", "plain"),
    ("tag on the fridge door that adds milk to the shopping list", "duplicate", "i022", "plain"),
    ("tag in my running jacket: tap after a run to keep my habit streak going", "duplicate", "i091", "plain"),
    ("tag on the coffee table that switches the lights to movie mode", "duplicate", "i014", "plain"),
    ("tag on the guitar amp that starts my practice playlist", "duplicate", "i016|i035", "plain"),
    ("tag on my headphone case that connects the headphones to my phone", "duplicate", "i088|i069", "plain"),
    ("sticker on the router so visitors can join the wifi", "duplicate", "i043", "short"),
    ("tag at the door that tells me if the back window is still open before I leave", "duplicate", "i084", "plain"),
    ("tag in my car that texts my wife I'm on my way home", "duplicate", "i041", "plain"),
    ("tag on the baby monitor that opens its manual", "duplicate", "i020", "short"),
    ("tag on the kids' bedroom door that starts a bedtime story on the speaker", "duplicate", "i012|i081", "plain"),
    ("tap the printer to print without setting it up", "duplicate", "i071", "short"),
    ("tag in my wallet that calls my sister if I have an emergency", "duplicate", "i095", "plain"),
    ("tag on each jar of homemade jam that shows the recipe and when I made it", "duplicate", "i105|i051", "plain"),
]


def split(text):
    """TUNE or TEST, decided by a hash of the text: fixed, random-looking, about half each."""
    return "TEST" if int(hashlib.sha256(text.encode()).hexdigest(), 16) % 2 else "TUNE"


TUNE = [c for c in CASES if split(c[0]) == "TUNE"]
TEST = [c for c in CASES if split(c[0]) == "TEST"]
